### ISSUE TITLE
Logo Design Offer For ParallaxImageView

### ISSUE THREAD

**Issue by iqbalhood** [abdularis/ParallaxImageView#2]
Hello Sir. I'm a UI/UX and Graphics Designer. 
I want propose a logo for your github project.
Would you mind if I propose logo for your application as my Open Source Contribution?

Thanks before.
Regards,
@iqbalhood

**Comment by abdularis** [comment]
It would be very cool to have a logo/icon for this project!

**Comment by iqbalhood** [comment]
Hello sir @abdularis ,
These are my logo proposal for your project. 
![alpha](https://user-images.githubusercontent.com/1563756/42375872-38a97dac-8147-11e8-92d1-6b1a229d1234.jpg)

I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.

I'll provide all file types and sizes you needed.

Hope you like it :)

**Comment by iqbalhood** [comment]
Hello sir @abdularis ,
These are my logo proposal for your project.

![parallax](https://user-images.githubusercontent.com/1563756/42385948-66eaf8fa-8168-11e8-8b6c-5807b6446263.jpg)



I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.

I'll provide all file types and sizes you needed.

Hope you like it :)

**Comment by abdularis** [comment]
Great!, I like your design, is 'a' letter stands for android?. 
What do you think if we remove the 'a' circle in the logo? just to compare which looks better

**Comment by iqbalhood** [comment]
The 'a' letter is stands for 'alpha' an angle subtended by a line on a point from 'parallax' text concept (https://en.wikipedia.org/wiki/Parallax) the sentences that you use in this library.

![screen shot 2018-07-06 at 21 16 40](https://user-images.githubusercontent.com/1563756/42383614-ee21238c-8161-11e8-9633-a1fcbe3dff60.png)

**Comment by abdularis** [comment]
Wow, excellent!
I'll add it in the project soon

**Comment by iqbalhood** [comment]
Hello Sir I Have Create Pull Request (Adding Logo to your project and Modify Readme.md)
https://github.com/abdularis/ParallaxImageView/pull/3

**Comment by abdularis** [comment]
:tada: It looks great, I'll close the issue
