### ISSUE TITLE
Paralaxx not working in Glide

### ISSUE THREAD

**Issue by Bekakk** [abdularis/ParallaxImageView#5]
Hi
I'm using your library,I have little issue.
Parallax effect not working when I try to create rounded corners image with Glide
Here is a my Glide code

//        val radius = context.resources.getDimensionPixelSize(R.dimen.dimen_p_15)
//        GlideApp.with(context)
//                .load(imageUrl)
//                .transform(CenterCrop(),RoundedCorners(radius))
//                .transition(DrawableTransitionOptions.withCrossFade()).into(imageView)](url)

do you have any solutions ?
thanks

**Comment by abdularis** [comment]
Maybe glide crop the image to fit the width/height of the image view, so it the image could not be scrolled inside imageview to make parallax effect
